
# app/config/routing.yml
root_show:
    path:      /
    defaults:  { _controller: AppBundle:Root:show }
abeja_show:
    path:      /abeja
    defaults:  { _controller: AppBundle:Abeja:show }
caballo_show:
    path:      /caballo
    defaults:  { _controller: AppBundle:Caballo:show }
<<<<<<< HEAD
competitionCreator_show:
    path:       /crearEvento
    defaults:   { _controller:  AppBundle:CompetitionCreator:show}
=======
root_create:
    path:      /create
    defaults:  { _controller: AppBundle:Root:create }
>>>>>>> 191dafc35bd6d9f17e576ba7dc1487a229d5e963
